function actionHelper() {
  const ACTIONS = {
    UPDATE_LOADING: 'UPDATE_LOADING',
    RESET_LOADING: 'RESET_LOADING',
    UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
    RESET_CURRENT_USER: 'RESET_CURRENT_USER',
    UPDATE_USER: 'UPDATE_USER',
    RESET_USER: 'RESET_USER',
  };

  return ACTIONS;
}

export default actionHelper;
